apiVersion: batch/v1
kind: Job
metadata:
  name: cockroachdb-connect-add
  namespace: caos-zitadel
  labels:
    app.kubernetes.io/name: cockroach-add
spec:
  backoffLimit: 3
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - command:
            - /bin/bash
            - -c
            - |-
              cockroach sql --certs-dir=/cockroach/cockroach-certs --host=${ZITADEL_E2E_DBHOST} --port=${ZITADEL_E2E_DBPORT} -e "CREATE USER IF NOT EXISTS ${ZITADEL_E2E_DBUSER};GRANT admin TO ${ZITADEL_E2E_DBUSER} WITH ADMIN OPTION;"
          image: ghcr.io/caos/zitadel-crbackup:${ZITADEL_E2E_TAG}
          imagePullPolicy: Always
          name: bucket
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /cockroach/cockroach-certs
              name: client-certs
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
      volumes:
        - name: client-certs
          secret:
            defaultMode: 256
            secretName: cockroachdb.client.root