codecov:
    notify:
      require_ci_to_pass: yes  
coverage:
    precision: 2
    round: down
    range: "70...100"
    status:
        project: yes
        patch: yes
        changes: no  
parsers:
    gcov:
        branch_detection:
            conditional: yes
            loop: yes
            method: no
            macro: no  
comment:
    layout: "header, diff"
    behavior: default
    require_changes: no

ignore:
  - ".artifacts"
  - ".codecov"
  - ".github" 
  - "build"
  - "docs"
  - "guides"
  - "console"
  - "openapi"
  - "statik"
  - "**.pb.go"
  - "**.proto.mock.go"
  - "**.pb.*.go"
  - "**.gen.go "
  - "openapi/**/*.json"
  - "/internal/api/assets/authz.go"
  - "/internal/api/assets/router.go"
  - "/internal/api/ui/console/static/*"
