version: '3.8'

services:
  zitadel:
    restart: always
    networks:
      - zitadel
    image: ghcr.io/zitadel/zitadel:v2.0.0-v2-alpha.24-amd64
    command: admin start-from-init --config /example-zitadel-config.yaml --config /example-zitadel-secrets.yaml --steps /example-zitadel-init-steps.yaml --masterkey "${ZITADEL_MASTERKEY}"
    healthcheck:
      test: ["CMD", "zitadel", "admin", "status", "health"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 40s
    depends_on:
      my-cockroach-db:
        condition: service_healthy
    ports:
      - 8080:8080
    volumes:
      - ./example-zitadel-config.yaml:/
      - ./example-zitadel-secrets.yaml:/
      - ./example-zitadel-init-steps.yaml:/

  my-cockroach-db:
    restart: always
    networks:
      - zitadel
    image: cockroachdb/cockroach:v22.1.0
    command: start-single-node --insecure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
    ports:
      - 9090:8080
      - 26257:26257

networks:
  zitadel:
