name: "Console Netlify Deployment"
on:
  push:
    branches:
      - cnsl-rhl-nav

jobs:
  build:
    name: Build ZITADEL Console
    runs-on: ubuntu-18.04
    steps:
      - name: Source checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/console/Dockerfile
          platforms: linux/amd64
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,scope=${{ github.workflow }},mode=max
          outputs: type=local,dest=/build
      - uses: actions/upload-artifact@v2
        with:
          name: zitadel-console
          path: /build
  deploy:
    name: "Deploy to Netlify"
    needs: build
    steps:
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.MY_TOKEN_SECRET }}
          NETLIFY_DEPLOY_TO_PROD: true
