name: End-to-end tests
on:
  push:
    branches-ignore:
      - master
  workflow_dispatch:
jobs:
  build-console:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          ## Workaround until https://github.com/docker/build-push-action/issues/252#issuecomment-804898823 is merged
          version: v0.6.0
          buildkitd-flags: --debug

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/console/Dockerfile
          platforms: linux/amd64
          #          cache-from: type=gha,scope=${{ github.workflow }} (https://github.com/caos/zitadel/issues/2102)
          cache-to: type=gha,scope=${{ github.workflow }},mode=max
          outputs: type=local,dest=/tmp/zitadel-console

      - shell: bash
        run: |
          ls -la

  cypress-run:
    runs-on: ubuntu-18.04
    container: cypress/browsers:node14.17.0-chrome91-ff89
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2.11.7
        with:
          working-directory: ./console
          build: npm run build
          start: npm start
          browser: chrome
          wait-on: "http://localhost:4200"
          wait-on-timeout: 120
        env:
          CYPRESS_consoleUrl: "http://localhost:4200"
          CYPRESS_apiCallsDomain: "zitadel.dev"
          CYPRESS_zitadelProjectResourceId: "70669147545070419"
          CYPRESS_serviceAccountKey: "${{secrets.E2E_SERVICEACCOUNT_KEY}}"
          CYPRESS_org_owner_password: "${{secrets.E2E_ORG_OWNER_PW}}"
          CYPRESS_org_owner_viewer_password: "${{secrets.E2E_ORG_OWNER_VIEWER_PW}}"
          CYPRESS_org_project_creator_password: "${{secrets.E2E_ORG_PROJECT_CREATOR_PW}}"
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: console/cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: console/cypress/videos
