name: ZITADEL Release

on:
  #pull_request:
  push:
    tags-ignore:
      - "*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - name: Source checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker
          install: true
      - name: Build
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: v1.5.0
          args: release --snapshot --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          dry_run: true
          semantic_version: 19.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: goreleaser/goreleaser-action@v2
        name: Publish ZITADEL
        if: ${{ steps.semantic.outputs.new-release-published == 'true' }}
        with:
          distribution: goreleaser
          version: v1.5.0
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ steps.semantic.outputs.release-version }} # I think this line is not needed. Nevertheless, it's explicit
      - name: Publish gRPC clients
        uses: actions/upload-artifact@v2
        if: ${{ steps.semantic.outputs.new-release-published == 'true' }}
        with:
          name: grpc-clients
          path: .artifacts/grpc
      - name: Publish console
        uses: actions/upload-artifact@v2
        if: ${{ steps.semantic.outputs.new-release-published == 'true' }}
        with:
          name: console
          path: .artifacts/console
      - name: Publish go coverage
        uses: codecov/codecov-action@v1
        with:
          files: .artifacts/codecov/profile.cov
          name: go-codecov
