name: ZITADEL Release

on:
  push:
    tags-ignore:
      - "*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Build:
    runs-on: ubuntu-20.04
    env:
      DOCKER_BUILDKIT: 1
      GOPATH: /home/runner/work/zitadel/zitadel
      WORKDIR: /home/runner/work/zitadel/zitadel/src/github.com/caos/zitadel
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Source checkout
        uses: actions/checkout@v2
        with:
          path: src/github.com/caos/zitadel
      - run: pwd
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker
          install: true
      - name: Test
        run: docker build -f build/zitadel/Dockerfile . -t zitadel-go-test --target go-codecov -o .artifacts/codecov
        working-directory: ${{ env.WORKDIR }}
      - name: Build ZITADEL
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: v1.5.0
          args: release --snapshot
          workdir: ${{env.WORKDIR}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          dry_run: false
          semantic_version: 19.0.2
          working_directory: ${{env.WORKDIR}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Google Container Registry Login
        if: ${{ github.event_name == 'workflow_dispatch' && steps.semantic.outputs.new_release_published == 'true' }}
        run: |
          echo "${{ secrets.GCR_JSON_KEY_BASE64 }}" | \
          base64 -d | \
          docker login -u _json_key --password-stdin https://eu.gcr.io
      - uses: goreleaser/goreleaser-action@v2
        name: Publish ZITADEL
        if: ${{ github.event_name == 'workflow_dispatch' && steps.semantic.outputs.new_release_published == 'true' }}
        with:
          distribution: goreleaser
          version: v1.5.0
          args: release --rm-dist
          workdir: ${{env.WORKDIR}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ steps.semantic.outputs.release-version }} # I think this line is not needed. Nevertheless, it's explicit
      - name: Publish gRPC clients
        uses: actions/upload-artifact@v2
        if: ${{ github.event_name == 'workflow_dispatch' && steps.semantic.outputs.new_release_published == 'true' }}
        with:
          name: grpc-clients
          path: ${{env.WORKDIR}}/.artifacts/grpc
      - name: Publish console
        uses: actions/upload-artifact@v2
        if: ${{ github.event_name == 'workflow_dispatch' && steps.semantic.outputs.new_release_published == 'true' }}
        with:
          name: console
          path: ${{env.WORKDIR}}/.artifacts/console
      - name: Publish go coverage
        uses: codecov/codecov-action@v1
        with:
          files: ${{env.WORKDIR}}/.artifacts/codecov/profile.cov
          name: go-codecov
